baseurl = "/"
languageCode = "en-us"
theme = "terminal"
paginate = 5
title = "Manaus"


[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 100

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = false

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # set a custom favicon (default is a `themeColor` square)
  # favicon = "favicon.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # oneHeadingSize = true # default

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default

  mns_url = 'http://manaus:8080/'

[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = ""
  site = ""

[languages]
  [languages.en]
    languageName = "English"
    title = "Manaus"
    subtitle = "A simple, retro theme for Hugo"
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "Manaus"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "profit_1d"
        name = "Profit 1d"
        url = "/profit_1d"
      [[languages.en.menu.main]]
        identifier = "profit_7d"
        name = "Profit 7d"
        url = "/profit_7d"
      [[languages.en.menu.main]]
        identifier = "profit_30d"
        name = "Profit 30d"
        url = "/profit_30d"
      [[languages.en.menu.main]]
        identifier = "profit_90d"
        name = "Profit 90d"
        url = "/profit_90d"
      [[languages.en.menu.main]]
        identifier = "progress_1d"
        name = "Progress 1d"
        url = "/progress_1d"
      [[languages.en.menu.main]]
        identifier = "progress_7d"
        name = "Progress 7d"
        url = "/progress_7d"
      [[languages.en.menu.main]]
        identifier = "progress_30d"
        name = "Progress 30d"
        url = "/progress_30d"
      [[languages.en.menu.main]]
        identifier = "progress_90d"
        name = "Progress 90d"
        url = "/progress_90d"
      [[languages.en.menu.main]]
        identifier = "Bets"
        name = "Bets"
        url = "/bets"
      [[languages.en.menu.main]]
        identifier = "Actions"
        name = "Actions"
        url = "/actions"
